[masters]
master ansible_host=3.76.99.90 ansible_user=admin

[workers]
worker1 ansible_host=35.159.228.187 ansible_user=admin
worker2 ansible_host=3.78.230.252 ansible_user=admin

[k8s_cluster:children]
masters
workers


